# Generated by Django 4.2.19 on 2025-03-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код статуса')),
                ('name', models.CharField(max_length=100, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус заявки',
                'verbose_name_plural': 'Статусы заявок',
            },
        ),
        migrations.RemoveField(
            model_name='bid',
            name='status',
        ),
        migrations.AddField(
            model_name='bid',
            name='statuses',
            field=models.ManyToManyField(to='therapy.bidstatus', verbose_name='Статусы заявки'),
        ),
    ]
